/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel;

/**
 *
 * @author emin yasir corut
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

    }

    public Main(Boolean isManager) {
        initComponents();

        if (!isManager) { //if a personnel enters the system, not an administrator, some powers are limited
            menuItemUser.setEnabled(false);
            MenuItem_Room.setEnabled(false);
            btn_Manager.setEnabled(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_redervstion = new javax.swing.JButton();
        btn_Manager = new javax.swing.JButton();
        btn_customer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemUser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItem_Room = new javax.swing.JMenu();
        menuItemRoomOptions = new javax.swing.JMenuItem();
        menuItemRoomTypeOptions = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemCustomerOptions = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemReservationAranges = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        back_login = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Royal Hotel Main Page");
        setLocation(new java.awt.Point(330, 85));
        setMaximumSize(new java.awt.Dimension(1140, 682));
        setMinimumSize(new java.awt.Dimension(1140, 682));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerLocation(230);
        jSplitPane1.setEnabled(false);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(new java.awt.Color(255, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\emin yasir corut\\Desktop\\HOTEL-Proje\\otel.jpg")); // NOI18N
        jPanel1.add(jLabel1);

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_redervstion.setIcon(new javax.swing.ImageIcon("C:\\Users\\emin yasir corut\\Desktop\\HOTEL-Proje\\Reservation.png")); // NOI18N
        btn_redervstion.setText("Reservation Aranges");
        btn_redervstion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_redervstion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redervstionActionPerformed(evt);
            }
        });
        jPanel2.add(btn_redervstion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 180, 180));

        btn_Manager.setIcon(new javax.swing.ImageIcon("C:\\Users\\emin yasir corut\\Desktop\\HOTEL-Proje\\user - Kopya.png")); // NOI18N
        btn_Manager.setText("User Settings");
        btn_Manager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManagerActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 180));
        btn_Manager.getAccessibleContext().setAccessibleName("btnUserSetting");

        btn_customer.setIcon(new javax.swing.ImageIcon("C:\\Users\\emin yasir corut\\Desktop\\HOTEL-Proje\\costumerr.png")); // NOI18N
        btn_customer.setText("Customer Options");
        btn_customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customerActionPerformed(evt);
            }
        });
        jPanel2.add(btn_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 180));

        jLabel2.setText("MANAGER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel3.setText("CUSTOMER");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        jLabel4.setText("RESERVATİON");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, -1, -1));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 680));

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1);

        jMenu1.setText("Manager");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuItemUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemUser.setText("User Settings");
        menuItemUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUserActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemUser);
        jMenu1.add(jSeparator1);

        MenuItem_Room.setText("Room");

        menuItemRoomOptions.setText("Room Options");
        menuItemRoomOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRoomOptionsActionPerformed(evt);
            }
        });
        MenuItem_Room.add(menuItemRoomOptions);

        menuItemRoomTypeOptions.setText("Room Type Options");
        menuItemRoomTypeOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRoomTypeOptionsActionPerformed(evt);
            }
        });
        MenuItem_Room.add(menuItemRoomTypeOptions);

        jMenu1.add(MenuItem_Room);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Customer");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuItemCustomerOptions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemCustomerOptions.setText("Customer Options");
        menuItemCustomerOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemCustomerOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCustomerOptionsActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemCustomerOptions);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reservation");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuItemReservationAranges.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReservationAranges.setText("Reservation Aranges");
        menuItemReservationAranges.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemReservationAranges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReservationArangesActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemReservationAranges);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Login");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        back_login.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        back_login.setText("Back Login");
        back_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_loginActionPerformed(evt);
            }
        });
        jMenu4.add(back_login);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customerActionPerformed
        // TODO add your handling code here:
        new Customer().setVisible(true);//Customer page opens. main page closes.
        this.dispose();
    }//GEN-LAST:event_btn_customerActionPerformed

    private void menuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUserActionPerformed
        // TODO add your handling code here:
        new Manager().setVisible(true);//USER page opens. main page closes.
        this.dispose();
    }//GEN-LAST:event_menuItemUserActionPerformed

    private void btn_ManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManagerActionPerformed
        // TODO add your handling code here:
        new Manager().setVisible(true);//MANAGER page opens. main page closes.
        this.dispose();
    }//GEN-LAST:event_btn_ManagerActionPerformed

    private void menuItemCustomerOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCustomerOptionsActionPerformed
        // TODO add your handling code here:
        new Customer().setVisible(true);//Customer page opens. main page closes.
        this.dispose();
    }//GEN-LAST:event_menuItemCustomerOptionsActionPerformed

    private void back_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_loginActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Login page opens. main page closes.
        new Login().setVisible(true);
    }//GEN-LAST:event_back_loginActionPerformed

    private void btn_redervstionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redervstionActionPerformed
        // TODO add your handling code here:
        this.dispose();  //Reservation page opens. main page closes.
        new Reservation().setVisible(true);
    }//GEN-LAST:event_btn_redervstionActionPerformed

    private void menuItemReservationArangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReservationArangesActionPerformed
        // TODO add your handling code here:
        this.dispose();  //Reservation page opens. main page closes.
        new Reservation().setVisible(true);
    }//GEN-LAST:event_menuItemReservationArangesActionPerformed

    private void menuItemRoomOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRoomOptionsActionPerformed
        // TODO add your handling code here:
        this.dispose();  //Room page opens. main page closes.
        new Room().setVisible(true);
    }//GEN-LAST:event_menuItemRoomOptionsActionPerformed

    private void menuItemRoomTypeOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRoomTypeOptionsActionPerformed
        // TODO add your handling code here:
        this.dispose();  //RoomType page opens. main page closes.
        new RoomType().setVisible(true);

    }//GEN-LAST:event_menuItemRoomTypeOptionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuItem_Room;
    private javax.swing.JMenuItem back_login;
    private javax.swing.JButton btn_Manager;
    private javax.swing.JButton btn_customer;
    private javax.swing.JButton btn_redervstion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuItem menuItemCustomerOptions;
    private javax.swing.JMenuItem menuItemReservationAranges;
    private javax.swing.JMenuItem menuItemRoomOptions;
    private javax.swing.JMenuItem menuItemRoomTypeOptions;
    private javax.swing.JMenuItem menuItemUser;
    // End of variables declaration//GEN-END:variables
}
